2025-09-25 23:35:41,599 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:47]
2025-09-25 23:35:50,586 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:47]
2025-09-25 23:36:57,866 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:47]
2025-09-26 19:46:34,859 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:47]
2025-09-26 19:47:05,741 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:47]
2025-09-26 19:47:14,190 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:47]
2025-09-26 19:47:17,303 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:47]
2025-09-26 20:08:17,464 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:47]
2025-09-26 20:08:24,075 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:47]
2025-09-26 20:08:33,886 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:47]
2025-09-26 20:10:03,944 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:47]
2025-09-26 20:11:46,461 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:47]
2025-09-26 20:47:10,023 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:49]
2025-09-26 20:47:13,400 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:49]
2025-09-26 20:55:59,874 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:48]
2025-09-26 21:18:47,003 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:48]
2025-09-26 21:26:24,024 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:50]
2025-09-26 21:26:51,517 ERROR: Exception on /register [GET] [in /home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/abdurr08/projects/microblog/app/routes.py", line 74, in register
    return render_template('register.html', title='Register', form=form)
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/abdurr08/projects/microblog/app/templates/register.html", line 2, in top-level template code
    {% import 'bootstrap_wtf.html' as wtf %}
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap_wtf.html
2025-09-26 21:30:05,082 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:50]
2025-09-29 13:13:08,152 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:58]
2025-09-29 13:13:19,399 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:58]
2025-09-29 15:14:19,516 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:58]
2025-09-29 15:14:28,220 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:58]
2025-09-29 17:07:29,648 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:58]
2025-09-29 17:07:38,920 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:58]
2025-09-29 17:11:12,238 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:58]
2025-09-29 17:22:14,317 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:58]
2025-09-29 19:44:12,692 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:58]
2025-09-29 19:49:18,149 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:58]
2025-09-29 19:49:23,757 ERROR: Exception on /translate [POST] [in /home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/abdurr08/projects/microblog/app/routes.py", line 222, in translate_text
    return {'text': translate(data['text'],
  File "/home/abdurr08/projects/microblog/app/translate.py", line 19, in translate
    return _('Error: the translation service failed.\nError code: ' + r.status_code)
TypeError: can only concatenate str (not "int") to str
2025-09-29 19:52:32,153 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:58]
2025-09-29 19:57:37,169 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:58]
2025-09-29 19:57:42,629 ERROR: Exception on /translate [POST] [in /home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/abdurr08/projects/microblog/app/routes.py", line 222, in translate_text
    return {'text': translate(data['text'],
  File "/home/abdurr08/projects/microblog/app/translate.py", line 11, in translate
    'Ocp-Apim-Subscription-Region': app.config['MS_TRANSLATOR_REGION'],  # add this in config
KeyError: 'MS_TRANSLATOR_REGION'
2025-09-29 19:58:47,865 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:58]
2025-09-29 19:58:52,992 ERROR: Exception on /translate [POST] [in /home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/abdurr08/.pyenv/versions/flask-env/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/abdurr08/projects/microblog/app/routes.py", line 222, in translate_text
    return {'text': translate(data['text'],
  File "/home/abdurr08/projects/microblog/app/translate.py", line 11, in translate
    'Ocp-Apim-Subscription-Region': app.config['MS_TRANSLATOR_REGION'],  # add this in config
KeyError: 'MS_TRANSLATOR_REGION'
2025-09-29 19:59:28,355 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:58]
2025-09-29 20:03:19,991 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:58]
2025-09-29 20:06:44,773 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:58]
2025-09-29 20:17:05,046 INFO: Microblog startup [in /home/abdurr08/projects/microblog/app/__init__.py:58]
